---

- hosts: tacoserver
  sudo: yes
  tasks:
    - name: "Instalar node.js"
      apt: name=nodejs state=present

    - name: "Instalar forever"
      npm: name=forever global=yes state=present

    - name: "Iniciar la aplicación"
      npm: forever start /opt/software/tacoapp/tacos.js
